import type { Restaurant, Event, Activity, AutismProgram, SocialGroup } from "@shared/schema";

// Sample Erie, PA restaurant data
export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "El Canelo Mexican Restaurant",
    category: "Mexican",
    categories: ["Mexican"],
    address: "2709 Parade St, Erie, PA 16504",
    phone: "(814) 453-6288",
    description: "Authentic Mexican cuisine with fresh ingredients and traditional recipes. Known for their flavorful tacos, enchiladas, and house-made salsas.",
    priceRange: "$$",
    rating: 4.5,
    hours: "11:00 AM - 9:00 PM",
    features: ["Dine-in", "Takeout", "Delivery"]
  },
  {
    id: "2",
    name: "Federal Hill Smokehouse",
    category: "BBQ",
    categories: ["BBQ", "American"],
    address: "2609 Peach St, Erie, PA 16508",
    phone: "(814) 920-4227",
    website: "https://www.federalhillsmokehouse.com",
    description: "Award-winning BBQ with slow-smoked meats, homemade sides, and craft beer selection. Dog-friendly patio available.",
    priceRange: "$$",
    rating: 4.7,
    hours: "11:00 AM - 9:00 PM",
    features: ["Dine-in", "Takeout", "Pet Friendly", "Outdoor Seating"]
  },
  {
    id: "3",
    name: "Bay House Oyster Bar & Restaurant",
    category: "Seafood",
    categories: ["Seafood", "Fine Dining"],
    address: "6 Sassafras Pier, Erie, PA 16507",
    phone: "(814) 920-9990",
    website: "https://www.bayhousepier6.com",
    description: "Erie's only fresh oyster bar offering stunning waterfront views, fresh seafood, and an exceptional dining experience.",
    priceRange: "$$$",
    rating: 4.8,
    hours: "4:00 PM - 10:00 PM",
    features: ["Dine-in", "Waterfront", "Full Bar", "Reservations"]
  },
  {
    id: "4",
    name: "Pineapple Eddie Southern Bistro",
    category: "American",
    categories: ["American", "Fine Dining"],
    address: "1402 W 10th St, Erie, PA 16502",
    phone: "(814) 454-1010",
    description: "Southern-inspired cuisine with a creative twist. Upscale dining featuring locally sourced ingredients.",
    priceRange: "$$$",
    rating: 4.6,
    hours: "5:00 PM - 9:00 PM",
    features: ["Dine-in", "Full Bar", "Reservations"]
  },
  {
    id: "5",
    name: "Khao Thai",
    category: "Asian",
    categories: ["Asian"],
    address: "36 N Park Row, Erie, PA 16501",
    phone: "(814) 454-4069",
    description: "Authentic Thai cuisine with fresh ingredients. Try their famous Pad Thai and curry dishes.",
    priceRange: "$$",
    rating: 4.4,
    hours: "11:00 AM - 9:00 PM",
    features: ["Dine-in", "Takeout", "Vegetarian Options"]
  },
  {
    id: "6",
    name: "Tandoori Hut",
    category: "Indian",
    categories: ["Indian", "Vegetarian"],
    address: "2060 Edinboro Rd, Erie, PA 16509",
    phone: "(814) 868-9070",
    description: "Traditional Indian cuisine with a variety of vegetarian and meat options. Known for their tandoori dishes and naan bread.",
    priceRange: "$$",
    rating: 4.3,
    hours: "11:30 AM - 9:30 PM",
    features: ["Dine-in", "Takeout", "Lunch Buffet", "Vegetarian Options"]
  },
  {
    id: "7",
    name: "Sara's Diner",
    category: "American",
    categories: ["American", "Breakfast"],
    address: "25 Peninsula Dr, Erie, PA 16505",
    phone: "(814) 833-1957",
    website: "https://sarasandsallys.com",
    description: "Beloved seasonal stop at the entrance to Presque Isle State Park. Famous for Erie-made Smith hot dogs and orange vanilla twists.",
    priceRange: "$",
    rating: 4.5,
    hours: "11:00 AM - 8:00 PM (Seasonal)",
    features: ["Takeout", "Family Friendly", "Ice Cream"]
  },
  {
    id: "8",
    name: "Cloud 9 Wine Bar & Restaurant",
    category: "Fine Dining",
    categories: ["Fine Dining", "Mediterranean"],
    address: "25 E 10th St, Erie, PA 16501",
    phone: "(814) 870-9007",
    website: "https://cloud9erie.com",
    description: "French-inspired upscale dining with thoughtfully chosen wines paired with skillfully prepared dishes.",
    priceRange: "$$$$",
    rating: 4.7,
    hours: "5:00 PM - 10:00 PM",
    features: ["Dine-in", "Wine Bar", "Reservations", "Fine Dining"]
  },
  {
    id: "9",
    name: "Bar Ronin",
    category: "Asian",
    categories: ["Asian", "American", "Bar & Grill"],
    address: "501 State St, Erie, PA 16501",
    phone: "(814) 520-8495",
    website: "https://roninerie.com",
    description: "American-Japanese fusion with shareable plates and standout cocktails. A chef-driven hotspot in downtown Erie.",
    priceRange: "$$$",
    rating: 4.8,
    hours: "4:00 PM - 11:00 PM",
    features: ["Dine-in", "Full Bar", "Cocktails", "Late Night"]
  },
  {
    id: "10",
    name: "Samurai Kitchen and Sushi",
    category: "Asian",
    categories: ["Asian", "Seafood"],
    address: "2767 W 12th St, Erie, PA 16505",
    phone: "(814) 836-0888",
    website: "https://www.samuraisushierie.com",
    description: "High-quality Japanese and Southeast Asian dishes with artful sushi rolls and vibrant entrees.",
    priceRange: "$$$",
    rating: 4.6,
    hours: "11:30 AM - 9:30 PM",
    features: ["Dine-in", "Takeout", "Sushi Bar"]
  },
  {
    id: "11",
    name: "Valerio's Italian Restaurant",
    category: "Italian",
    categories: ["Italian"],
    address: "544 W 18th St, Erie, PA 16502",
    phone: "(814) 452-4633",
    description: "Family-owned Italian restaurant serving homemade pasta, pizza, and classic Italian dishes since 1978.",
    priceRange: "$$",
    rating: 4.5,
    hours: "11:00 AM - 10:00 PM",
    features: ["Dine-in", "Takeout", "Family Style"]
  },
  {
    id: "12",
    name: "Shoreline Bar and Grille",
    category: "Bar & Grill",
    categories: ["Bar & Grill", "American", "Seafood"],
    address: "3 Bayfront Connector, Erie, PA 16507",
    phone: "(814) 455-1449",
    description: "Waterfront dining with panoramic views of Presque Isle Bay. Casual American fare with fresh seafood.",
    priceRange: "$$",
    rating: 4.3,
    hours: "11:00 AM - 10:00 PM",
    features: ["Dine-in", "Waterfront", "Outdoor Seating", "Full Bar"]
  },
  {
    id: "13",
    name: "Julius Restaurant",
    category: "Mexican",
    categories: ["Mexican"],
    address: "2835 W 26th St, Erie, PA 16506",
    phone: "(814) 835-3066",
    description: "Traditional Mexican cuisine with generous portions. Famous for their flan and authentic flavors.",
    priceRange: "$",
    rating: 4.4,
    hours: "10:00 AM - 9:00 PM",
    features: ["Dine-in", "Takeout", "Family Friendly"]
  },
  {
    id: "14",
    name: "Ippa Pizza Napoletana",
    category: "Pizza",
    categories: ["Pizza", "Italian"],
    address: "1503 State St, Erie, PA 16501",
    phone: "(814) 459-4772",
    description: "Authentic Neapolitan-style pizza made with fresh dough and imported ingredients. Available on major delivery apps.",
    priceRange: "$$",
    rating: 4.6,
    hours: "11:00 AM - 9:00 PM",
    features: ["Dine-in", "Takeout", "Delivery"]
  },
  {
    id: "15",
    name: "Sloppy Duck Saloon",
    category: "American",
    categories: ["American", "Seafood", "Bar & Grill"],
    address: "726 W Bayfront Pkwy, Erie, PA 16507",
    phone: "(814) 459-3625",
    website: "https://www.sloppyducksaloon.com",
    description: "Waterfront favorite known for the crispiest fried walleye sandwich. Seasonal outdoor seating with bay views.",
    priceRange: "$$",
    rating: 4.5,
    hours: "11:00 AM - 10:00 PM (Seasonal)",
    features: ["Dine-in", "Waterfront", "Full Bar", "Outdoor Seating"]
  },
  {
    id: "16",
    name: "Lucky Louie's Beer and Wieners",
    category: "American",
    categories: ["American", "Fast Food"],
    address: "8552 Peach St, Erie, PA 16509",
    phone: "(814) 866-5464",
    website: "https://luckylouiesbeerandwieners.com",
    description: "Unhinged and laid-back vibe with outrageous hot dog topping combinations, craft brews, and yard games.",
    priceRange: "$",
    rating: 4.4,
    hours: "11:00 AM - 9:00 PM",
    features: ["Dine-in", "Outdoor Seating", "Craft Beer", "Family Friendly"]
  },
  {
    id: "17",
    name: "Bakery on 5th",
    category: "Cafe",
    categories: ["Cafe", "Breakfast"],
    address: "2608 Parade St, Erie, PA 16504",
    phone: "(814) 454-2255",
    description: "Artisan bakery known for oversized croissants and Turkish coffee. Perfect stop for pastries and coffee.",
    priceRange: "$",
    rating: 4.6,
    hours: "7:00 AM - 3:00 PM",
    features: ["Dine-in", "Takeout", "Coffee", "Pastries"]
  },
  {
    id: "18",
    name: "Quaker Steak & Lube",
    category: "American",
    categories: ["American", "Bar & Grill"],
    address: "7851 Peach St, Erie, PA 16509",
    phone: "(814) 868-7923",
    website: "https://thelube.com",
    description: "Motor-themed restaurant with famous wings and duckpin bowling. Fun for the whole family.",
    priceRange: "$$",
    rating: 4.2,
    hours: "11:00 AM - 11:00 PM",
    features: ["Dine-in", "Bowling", "Full Bar", "Family Friendly"]
  },
  {
    id: "19",
    name: "Two45 Waterfront Grille",
    category: "Fine Dining",
    categories: ["Fine Dining", "American", "Seafood"],
    address: "55 W Bay Dr, Erie, PA 16507",
    phone: "(814) 454-2011",
    description: "Upscale dining inside the Sheraton Erie Bayfront Hotel with panoramic waterfront views and refined American cuisine.",
    priceRange: "$$$",
    rating: 4.5,
    hours: "6:30 AM - 10:00 PM",
    features: ["Dine-in", "Waterfront", "Breakfast", "Reservations"]
  },
  {
    id: "20",
    name: "Flagship City Food Hall",
    category: "American",
    categories: ["American", "Asian", "Mexican"],
    address: "22 N Park Row, Erie, PA 16501",
    phone: "(814) 204-9022",
    website: "https://www.flagshipcitydistrict.com/foodhall",
    description: "Multiple local vendors under one roof offering diverse kid-friendly options and local favorites.",
    priceRange: "$$",
    rating: 4.3,
    hours: "11:00 AM - 8:00 PM",
    features: ["Dine-in", "Multiple Vendors", "Family Friendly"]
  }
];

// Erie, PA events data - sourced from VisitErie.com
export const events: Event[] = [
  {
    id: "1",
    title: "Sensory Time at the expERIEnce Children's Museum",
    category: "Education",
    date: "2025-12-15",
    time: "11:00 AM",
    endTime: "12:00 PM",
    venue: "expERIEnce Children's Museum",
    address: "420 French St, Erie, PA 16507",
    description: "A special sensory-friendly time at the museum designed for children who benefit from a calmer, quieter environment. Reduced lighting and sound for a comfortable experience.",
    isFree: false,
    price: "Museum admission",
    ticketUrl: "https://www.visiterie.com/events/event/12/15/2025/sensory-time-at-the-experience-childrens-museum-11"
  },
  {
    id: "2",
    title: "Country Christmas at Port Farms",
    category: "Holiday",
    date: "2025-12-17",
    time: "5:00 PM",
    endTime: "9:00 PM",
    venue: "Port Farms",
    address: "2Portal Rd, Waterford, PA 16441",
    description: "Experience the magic of the holidays at Port Farms with thousands of lights, horse-drawn wagon rides, visits with Santa, holiday treats, and festive family fun.",
    isFree: false,
    price: "Varies",
    ticketUrl: "https://www.visiterie.com/events/event/12/17/2025/country-christmas-at-port-farms"
  },
  {
    id: "3",
    title: "Winter Wonderland at Asbury Woods",
    category: "Outdoor",
    date: "2025-12-18",
    time: "5:00 PM",
    endTime: "8:00 PM",
    venue: "Asbury Woods",
    address: "4105 Asbury Rd, Erie, PA 16506",
    description: "Walk through a winter wonderland with beautiful light displays, hot cocoa, crafts, and nature activities at this beloved Erie nature center.",
    isFree: false,
    price: "Varies",
    ticketUrl: "https://www.visiterie.com/events/event/12/18/2025/winter-wonderland-at-asbury-woods-3"
  },
  {
    id: "4",
    title: "Blitzen's at The Brewerie: Erie's Only Pop Up Christmas Bar",
    category: "Nightlife",
    date: "2025-12-18",
    time: "4:00 PM",
    endTime: "10:00 PM",
    venue: "The Brewerie at Union Station",
    address: "123 W 14th St, Erie, PA 16501",
    description: "Erie's only pop-up Christmas bar transforms The Brewerie into a winter wonderland with festive cocktails, holiday decor, and seasonal cheer. 21+ event.",
    isFree: true,
    ticketUrl: "https://www.visiterie.com/events/event/12/18/2025/blitzens-at-the-brewerie-eries-only-pop-up-christmas-bar"
  },
  {
    id: "5",
    title: "Presque Isle Lights 2025",
    category: "Holiday",
    date: "2025-12-19",
    time: "5:00 PM",
    endTime: "9:00 PM",
    venue: "Presque Isle State Park",
    address: "301 Peninsula Dr, Erie, PA 16505",
    description: "Drive through a spectacular display of over 100 illuminated exhibits and thousands of lights along Presque Isle's scenic roads. A beloved Erie holiday tradition!",
    isFree: false,
    price: "$10 per car",
    ticketUrl: "https://www.visiterie.com/events/event/12/19/2025/presque-isle-lights-2025"
  },
  {
    id: "6",
    title: "Erie Restaurant Week 2026",
    category: "Food & Drink",
    date: "2026-01-22",
    time: "All Day",
    venue: "Various Restaurants",
    address: "Downtown Erie & Surrounding Areas",
    description: "Erie's biggest culinary celebration! Sample prix-fixe menus and special offerings from dozens of Erie's best restaurants at special prices.",
    isFree: false,
    price: "Prix-fixe menus",
    ticketUrl: "https://www.visiterie.com/events/event/01/22/2026/erie-restaurant-week-2026"
  },
  {
    id: "7",
    title: "Erie SeaWolves Opening Night",
    category: "Sports",
    date: "2026-04-03",
    time: "6:05 PM",
    venue: "UPMC Park - Stadium Club",
    address: "110 E 10th St, Erie, PA 16501",
    description: "Kick off the baseball season with the Erie SeaWolves! Opening night festivities, fireworks, and family fun at UPMC Park.",
    isFree: false,
    price: "$10-$25",
    ticketUrl: "https://www.visiterie.com/events/event/04/03/2026/erie-seawolves-opening-night"
  },
  {
    id: "8",
    title: "Erie SeaWolves: Moon Mammoths Night",
    category: "Sports",
    date: "2026-05-29",
    time: "6:05 PM",
    venue: "UPMC Park",
    address: "110 E 10th St, Erie, PA 16501",
    description: "The Erie SeaWolves transform into the Moon Mammoths for this special themed night! Special jerseys, promotions, and fun for all ages.",
    isFree: false,
    price: "$10-$25",
    ticketUrl: "https://www.visiterie.com/events/event/05/29/2026/erie-seawolves-moon-mammoths-night"
  },
  {
    id: "9",
    title: "Erie Philharmonic Winter Concert",
    category: "Music",
    date: "2025-12-20",
    time: "7:30 PM",
    venue: "Warner Theatre",
    address: "811 State St, Erie, PA 16501",
    description: "Celebrate the holiday season with the Erie Philharmonic's annual winter concert featuring classical favorites and holiday music.",
    price: "$25-$65",
    isFree: false,
    ticketUrl: "https://eriephil.org"
  },
  {
    id: "10",
    title: "New Year's Eve Celebration Downtown",
    category: "Festival",
    date: "2025-12-31",
    time: "9:00 PM",
    endTime: "12:30 AM",
    venue: "Perry Square",
    address: "601 State St, Erie, PA 16501",
    description: "Ring in the new year with live music, food vendors, and the famous Erie ball drop at midnight.",
    isFree: true
  },
  {
    id: "11",
    title: "Erie Otters Hockey Game",
    category: "Sports",
    date: "2025-12-27",
    time: "7:00 PM",
    venue: "Erie Insurance Arena",
    address: "809 French St, Erie, PA 16501",
    description: "Cheer on the Erie Otters OHL hockey team as they take on their rivals. Family-friendly entertainment!",
    price: "$15-$35",
    isFree: false,
    ticketUrl: "https://www.ottershockey.com"
  },
  {
    id: "12",
    title: "Family Skate Night",
    category: "Family",
    date: "2025-12-22",
    time: "6:00 PM",
    endTime: "9:00 PM",
    venue: "Erie Insurance Arena",
    address: "809 French St, Erie, PA 16501",
    description: "Bring the whole family for a fun evening of ice skating. Skate rentals available.",
    price: "$8",
    isFree: false
  },
  {
    id: "13",
    title: "Erie Art Museum First Friday",
    category: "Arts",
    date: "2026-01-03",
    time: "7:00 PM",
    endTime: "10:00 PM",
    venue: "Erie Art Museum",
    address: "20 E 5th St, Erie, PA 16507",
    description: "Monthly celebration of arts and culture with live performances, gallery openings, and refreshments.",
    isFree: true
  },
  {
    id: "14",
    title: "Comedy Night at Jr's Last Laugh",
    category: "Nightlife",
    date: "2025-12-28",
    time: "8:00 PM",
    venue: "Jr's Last Laugh",
    address: "1402 State St, Erie, PA 16501",
    description: "Laugh the night away with nationally touring comedians at Erie's premier comedy club.",
    price: "$20",
    isFree: false
  },
  {
    id: "15",
    title: "Polar Plunge for Special Olympics",
    category: "Community",
    date: "2026-01-01",
    time: "12:00 PM",
    venue: "Presque Isle Beach 1",
    address: "Presque Isle State Park, Erie, PA 16505",
    description: "Take the plunge into Lake Erie to raise money for Special Olympics Pennsylvania. Registration required.",
    isFree: true,
    ticketUrl: "https://www.specialolympicspa.org"
  },
  {
    id: "16",
    title: "Winter Wine Festival",
    category: "Food & Drink",
    date: "2026-01-11",
    time: "1:00 PM",
    endTime: "5:00 PM",
    venue: "Mazza Vineyards",
    address: "11815 E Lake Rd, North East, PA 16428",
    description: "Sample award-winning wines from Lake Erie Wine Country with local cheese pairings and live music.",
    price: "$25",
    isFree: false
  },
  {
    id: "17",
    title: "Erie Playhouse: The Lion King Jr.",
    category: "Theater",
    date: "2025-12-29",
    time: "2:00 PM",
    venue: "Erie Playhouse",
    address: "13 W 10th St, Erie, PA 16501",
    description: "Disney's beloved story comes to life on stage in this family-friendly musical production.",
    price: "$15-$25",
    isFree: false,
    ticketUrl: "https://www.erieplayhouse.org"
  },
  {
    id: "18",
    title: "Bicentennial Tower Winter Hours",
    category: "Outdoor",
    date: "2025-12-20",
    time: "10:00 AM",
    endTime: "6:00 PM",
    venue: "Bicentennial Tower",
    address: "1 State St, Erie, PA 16507",
    description: "Erie's best view in every direction! The observation deck offers stunning views of Presque Isle Bay. Open Fri/Sat/Sun. Tower lit in holiday colors throughout December.",
    isFree: false,
    price: "$5"
  },
  {
    id: "19",
    title: "Splash Lagoon Family Fun Day",
    category: "Family",
    date: "2025-12-26",
    time: "10:00 AM",
    endTime: "8:00 PM",
    venue: "Splash Lagoon Indoor Water Park",
    address: "8091 Peach St, Erie, PA 16509",
    description: "Escape the cold at Splash Lagoon where it's always 84 degrees! Features nine water slides, pools, hot tubs, and a massive arcade. Ranked #2 Best Indoor Water Park in the U.S.",
    isFree: false,
    price: "Day passes available",
    ticketUrl: "https://www.splashlagoon.com"
  },
  {
    id: "20",
    title: "Live Jazz at Room 33",
    category: "Music",
    date: "2025-12-21",
    time: "8:00 PM",
    venue: "Room 33",
    address: "1033 State St, Erie, PA 16501",
    description: "Enjoy an evening of live jazz in an intimate speakeasy atmosphere. Craft cocktails available.",
    price: "$10",
    isFree: false
  }
];

// Sample activities/things to do data
export const activities: Activity[] = [
  {
    id: "1",
    name: "Presque Isle State Park",
    category: "Nature",
    audience: ["Kids", "Adults", "Family"],
    address: "301 Peninsula Dr, Erie, PA 16505",
    phone: "(814) 833-7424",
    website: "https://www.dcnr.pa.gov/StateParks/FindAPark/PresqueIsleStatePark",
    description: "Pennsylvania's most visited state park featuring 11 miles of sandy beaches, hiking trails, and stunning Lake Erie views.",
    hours: "5:00 AM - 11:00 PM",
    priceRange: "Free"
  },
  {
    id: "2",
    name: "ExpERIEnce Children's Museum",
    category: "Education",
    audience: ["Kids", "Family"],
    address: "420 French St, Erie, PA 16507",
    phone: "(814) 453-3743",
    website: "https://www.eriechildrensmuseum.org",
    description: "Interactive exhibits designed to inspire creativity and learning in children through hands-on play.",
    hours: "Tue-Sat 10:00 AM - 4:00 PM",
    priceRange: "$10"
  },
  {
    id: "3",
    name: "Erie Zoo",
    category: "Nature",
    audience: ["Kids", "Family"],
    address: "423 W 38th St, Erie, PA 16508",
    phone: "(814) 864-4091",
    website: "https://www.eriezoo.org",
    description: "Home to over 400 animals from around the world. Features a train ride, carousel, and seasonal attractions.",
    hours: "10:00 AM - 5:00 PM",
    priceRange: "$12-$14"
  },
  {
    id: "4",
    name: "Erie Maritime Museum & US Brig Niagara",
    category: "Arts & Culture",
    audience: ["Adults", "Family"],
    address: "150 E Front St, Erie, PA 16507",
    phone: "(814) 452-2744",
    website: "https://www.flagshipniagara.org",
    description: "Explore Erie's rich maritime history and tour the reconstructed US Brig Niagara, hero of the Battle of Lake Erie.",
    hours: "Thu-Sun 10:00 AM - 5:00 PM",
    priceRange: "$8-$10"
  },
  {
    id: "5",
    name: "Waldameer Park & Water World",
    category: "Entertainment",
    audience: ["Kids", "Adults", "Family"],
    address: "220 Peninsula Dr, Erie, PA 16505",
    phone: "(814) 838-3591",
    website: "https://www.waldameer.com",
    description: "Classic amusement park with roller coasters, water slides, and family rides. Free admission, pay-per-ride available.",
    hours: "Seasonal (May-Sept)",
    priceRange: "Free-$34"
  },
  {
    id: "6",
    name: "Erie Art Museum",
    category: "Arts & Culture",
    audience: ["Adults", "Family"],
    address: "20 E 5th St, Erie, PA 16507",
    phone: "(814) 459-5477",
    website: "https://www.erieartmuseum.org",
    description: "Regional art museum featuring American and international art spanning 5,000 years of creative expression.",
    hours: "Thu-Sun 11:00 AM - 5:00 PM",
    priceRange: "$8"
  },
  {
    id: "7",
    name: "Tom Ridge Environmental Center",
    category: "Nature",
    audience: ["Kids", "Adults", "Family"],
    address: "301 Peninsula Dr Suite 1, Erie, PA 16505",
    phone: "(814) 833-7424",
    description: "Free exhibits about Presque Isle's unique ecosystem, observation tower with panoramic views.",
    hours: "10:00 AM - 6:00 PM",
    priceRange: "Free"
  },
  {
    id: "8",
    name: "Peek'n Peak Resort",
    category: "Sports",
    audience: ["Adults", "Family"],
    address: "1405 Olde Rd, Clymer, NY 14724",
    phone: "(716) 355-4141",
    website: "https://www.pknpk.com",
    description: "Year-round resort offering skiing, snowboarding, golf, zip lining, and spa services.",
    hours: "Varies by season",
    priceRange: "$45-$85"
  },
  {
    id: "9",
    name: "Splash Lagoon Indoor Water Park",
    category: "Entertainment",
    audience: ["Kids", "Family"],
    address: "8091 Peach St, Erie, PA 16509",
    phone: "(814) 217-1111",
    website: "https://www.splashlagoon.com",
    description: "Indoor water park featuring slides, wave pools, and attractions for all ages. Perfect for year-round fun!",
    hours: "10:00 AM - 9:00 PM",
    priceRange: "$35-$50"
  },
  {
    id: "10",
    name: "Escape Game Erie",
    category: "Entertainment",
    audience: ["Adults", "Family"],
    address: "3003 W 12th St, Erie, PA 16505",
    phone: "(814) 315-9100",
    description: "Immersive escape room experiences with multiple themed rooms. Great for team building and family fun.",
    hours: "Tue-Sun 12:00 PM - 10:00 PM",
    priceRange: "$28-$35"
  },
  {
    id: "11",
    name: "Warner Theatre",
    category: "Arts & Culture",
    audience: ["Adults", "Family"],
    address: "811 State St, Erie, PA 16501",
    phone: "(814) 452-4857",
    website: "https://www.erieevents.com",
    description: "Historic 1931 movie palace now hosting concerts, Broadway shows, and special events.",
    hours: "Varies by event",
    priceRange: "Varies"
  },
  {
    id: "12",
    name: "Presque Isle Lighthouse",
    category: "Tours",
    audience: ["Adults", "Family"],
    address: "Presque Isle State Park, Erie, PA 16505",
    phone: "(814) 833-7424",
    description: "Historic lighthouse dating to 1873 offering tours and stunning views of Lake Erie.",
    hours: "Seasonal tours available",
    priceRange: "Free"
  },
  {
    id: "13",
    name: "Lake Erie Canopy Tours",
    category: "Outdoor",
    audience: ["Adults", "Family"],
    address: "5480 Rt 430, Bemus Point, NY 14712",
    phone: "(716) 720-9477",
    description: "Thrilling zipline adventure through the forest canopy with views of the lake region.",
    hours: "Seasonal",
    priceRange: "$65-$95"
  },
  {
    id: "14",
    name: "Millcreek Mall",
    category: "Shopping",
    audience: ["Adults", "Family"],
    address: "5800 Peach St, Erie, PA 16565",
    phone: "(814) 868-9000",
    website: "https://www.millcreekmall.net",
    description: "Region's largest shopping destination with over 150 stores, restaurants, and entertainment.",
    hours: "10:00 AM - 9:00 PM",
    priceRange: "Varies"
  },
  {
    id: "15",
    name: "Bicentennial Tower",
    category: "Tours",
    audience: ["Adults", "Family"],
    address: "1 State St, Erie, PA 16507",
    phone: "(814) 455-6055",
    description: "Observation tower on the bayfront offering 360-degree views of Erie, Presque Isle, and Lake Erie.",
    hours: "10:00 AM - 8:00 PM (Seasonal)",
    priceRange: "$4"
  }
];

// Sample autism programs data
export const autismPrograms: AutismProgram[] = [
  {
    id: "1",
    name: "Autism Society of Northwestern Pennsylvania",
    organization: "Autism Society NWPA",
    description: "Providing education, advocacy, and support services for individuals with autism and their families throughout Northwestern Pennsylvania.",
    address: "3340 Peach St, Erie, PA 16508",
    phone: "(814) 455-3540",
    email: "info@autismnwpa.org",
    website: "https://www.autismnwpa.org",
    services: ["Support Groups", "Educational Workshops", "Advocacy", "Resource Navigation", "Family Events"],
    accessibility: ["Sensory-Friendly Environment", "Visual Supports", "Trained Staff"]
  },
  {
    id: "2",
    name: "Barber National Institute",
    organization: "Barber National Institute",
    description: "Comprehensive services for children and adults with autism including education, employment, and residential programs.",
    ageRange: "All ages",
    address: "100 Barber Pl, Erie, PA 16507",
    phone: "(814) 453-7661",
    website: "https://www.bfrce.org",
    services: ["Early Intervention", "Special Education", "Adult Day Programs", "Employment Services", "Residential Services", "Behavioral Health"],
    accessibility: ["Wheelchair Accessible", "Sensory Rooms", "ABA Therapy"]
  },
  {
    id: "3",
    name: "Achievement Center",
    organization: "The Achievement Center",
    description: "Providing therapy, education, and support services for children with developmental delays and disabilities.",
    ageRange: "Birth to 21 years",
    address: "4800 Zuck Rd, Erie, PA 16506",
    phone: "(814) 459-2755",
    website: "https://www.achievementctr.org",
    services: ["Occupational Therapy", "Speech Therapy", "Physical Therapy", "Social Skills Groups", "Summer Programs"],
    accessibility: ["Therapy Equipment", "Sensory Integration", "Individualized Plans"]
  },
  {
    id: "4",
    name: "Autism Diagnostic Services - UPMC Children's",
    organization: "UPMC Children's Hospital",
    description: "Comprehensive diagnostic evaluations and ongoing care for children with autism spectrum disorders.",
    ageRange: "Children and Adolescents",
    address: "310 E 2nd St, Erie, PA 16507",
    phone: "(814) 877-8200",
    website: "https://www.chp.edu/our-services/autism",
    services: ["Diagnostic Evaluations", "Developmental Assessments", "Care Coordination", "Family Support"],
    accessibility: ["Hospital Setting", "Specialized Medical Team", "Insurance Accepted"]
  },
  {
    id: "5",
    name: "GECAC Early Intervention",
    organization: "Greater Erie Community Action Committee",
    description: "Early intervention services for infants and toddlers with developmental delays or at risk for delays.",
    ageRange: "Birth to 3 years",
    address: "18 W 9th St, Erie, PA 16501",
    phone: "(814) 459-4581",
    website: "https://www.gecac.org",
    services: ["In-Home Services", "Family Training", "Developmental Therapy", "Service Coordination"],
    accessibility: ["Home-Based Services", "Free Services", "Multilingual Support"]
  },
  {
    id: "6",
    name: "Sarah Reed Children's Center",
    organization: "Sarah Reed Children's Center",
    description: "Mental health and autism services for children including residential treatment and outpatient programs.",
    ageRange: "5-18 years",
    address: "2445 W 34th St, Erie, PA 16506",
    phone: "(814) 838-1954",
    website: "https://www.sarahreed.org",
    services: ["Residential Treatment", "Outpatient Therapy", "Crisis Services", "School-Based Programs"],
    accessibility: ["24/7 Support", "Specialized Staff", "Crisis Intervention"]
  },
  {
    id: "7",
    name: "Sensory-Friendly Movie Events",
    organization: "Tinseltown Erie",
    description: "Regular sensory-friendly movie screenings with adjusted lighting, lower volume, and freedom to move around.",
    address: "1910 Rotunda Dr, Erie, PA 16509",
    phone: "(814) 866-0123",
    services: ["Sensory-Friendly Screenings", "Reduced Stimulation", "Family-Friendly Environment"],
    accessibility: ["Lights Dimmed", "Lower Volume", "Movement Allowed", "Wheelchair Accessible"]
  },
  {
    id: "8",
    name: "Autism-Friendly Swim Program",
    organization: "Erie Family YMCA",
    description: "Specialized swimming lessons for individuals with autism in a calm, supportive environment.",
    ageRange: "All ages",
    address: "31 W 10th St, Erie, PA 16501",
    phone: "(814) 452-3261",
    website: "https://www.ymcaerie.org",
    services: ["Private Lessons", "Small Group Classes", "Sensory-Friendly Times", "Trained Instructors"],
    accessibility: ["Pool Accessibility", "Quiet Hours", "Visual Schedules"]
  }
];

// Sample social groups data
export const socialGroups: SocialGroup[] = [
  {
    id: "1",
    name: "Erie Young Professionals",
    category: "Professional Networking",
    description: "Networking group for professionals ages 21-40 focused on career development, community involvement, and social connections.",
    meetingSchedule: "Monthly networking events",
    location: "Various locations throughout Erie",
    contactEmail: "info@erieyps.org",
    website: "https://www.erieyps.org",
    membershipFee: "$50/year"
  },
  {
    id: "2",
    name: "Erie Running Club",
    category: "Sports & Fitness",
    description: "Community of runners of all skill levels meeting for group runs, training programs, and local race participation.",
    meetingSchedule: "Saturdays 8:00 AM, Tuesdays 6:00 PM",
    location: "Presque Isle State Park",
    contactEmail: "erierunners@gmail.com",
    membershipFee: "Free"
  },
  {
    id: "3",
    name: "Lake Erie Hiking Club",
    category: "Outdoor Recreation",
    description: "Explore the trails and natural beauty of the Lake Erie region with fellow outdoor enthusiasts.",
    meetingSchedule: "Weekly hikes on weekends",
    location: "Various trails in Erie County",
    website: "https://www.meetup.com/lake-erie-hiking-club",
    membershipFee: "Free"
  },
  {
    id: "4",
    name: "Erie Moms Group",
    category: "Parenting",
    description: "Support network for mothers in the Erie area featuring playdates, mom nights out, and family activities.",
    meetingSchedule: "Multiple weekly events",
    location: "Various family-friendly locations",
    contactEmail: "eriemomsgroup@gmail.com",
    membershipFee: "Free"
  },
  {
    id: "5",
    name: "Erie Board Game Enthusiasts",
    category: "Hobbies",
    description: "Weekly gatherings for board game lovers to play both classic and modern tabletop games.",
    meetingSchedule: "Wednesdays 6:00 PM",
    location: "Time Warp Games, 5865 Peach St",
    membershipFee: "Free"
  },
  {
    id: "6",
    name: "Erie Photography Club",
    category: "Arts & Creative",
    description: "Club for photographers of all skill levels to share work, learn techniques, and participate in photo walks.",
    meetingSchedule: "2nd Tuesday of each month",
    location: "Erie Art Museum",
    contactEmail: "eriephotoclub@gmail.com",
    membershipFee: "$25/year"
  },
  {
    id: "7",
    name: "Erie Rotary Club",
    category: "Service & Volunteer",
    description: "International service organization focused on community service, ethical standards, and goodwill.",
    meetingSchedule: "Thursdays 12:00 PM",
    location: "Sheraton Erie Bayfront Hotel",
    website: "https://www.erierotary.org",
    membershipFee: "Annual dues apply"
  },
  {
    id: "8",
    name: "Erie Writers' Workshop",
    category: "Arts & Creative",
    description: "Supportive community for writers of all genres to share work, receive feedback, and improve craft.",
    meetingSchedule: "1st and 3rd Saturdays 10:00 AM",
    location: "Blasco Memorial Library",
    contactEmail: "eriewriters@gmail.com",
    membershipFee: "Free"
  },
  {
    id: "9",
    name: "Erie Foodies",
    category: "Food & Dining",
    description: "Group of food enthusiasts exploring Erie's dining scene, hosting potlucks, and sharing culinary adventures.",
    meetingSchedule: "Monthly restaurant outings",
    location: "Various Erie restaurants",
    website: "https://www.meetup.com/erie-foodies",
    membershipFee: "Free"
  },
  {
    id: "10",
    name: "Erie Ski Club",
    category: "Sports & Fitness",
    description: "Winter sports enthusiasts organizing ski trips, lessons, and social events for members of all skill levels.",
    meetingSchedule: "Seasonal meetings and trips",
    location: "Peek'n Peak and other resorts",
    website: "https://www.erieskiclub.org",
    membershipFee: "$45/year"
  },
  {
    id: "11",
    name: "Single Parents of Erie",
    category: "Parenting",
    description: "Support and social group for single parents to connect, share experiences, and organize family activities.",
    meetingSchedule: "Bi-weekly gatherings",
    location: "Various family-friendly locations",
    contactEmail: "singleparentserie@gmail.com",
    membershipFee: "Free"
  },
  {
    id: "12",
    name: "Erie Garden Club",
    category: "Hobbies",
    description: "Gardening enthusiasts sharing knowledge, hosting plant sales, and beautifying Erie through community projects.",
    meetingSchedule: "3rd Wednesday of each month",
    location: "Frontier Park",
    contactPhone: "(814) 555-1234",
    membershipFee: "$20/year"
  }
];
