import type { Restaurant, Event, Activity, AutismProgram, SocialGroup, Business } from "@shared/schema";

// Sample Erie, PA restaurant data
export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Sara's Diner",
    category: "American",
    categories: ["American", "Breakfast"],
    address: "25 Peninsula Dr, Erie, PA 16505",
    phone: "(814) 833-1957",
    website: "https://sarasandsallys.com",
    description: "Beloved seasonal stop at the entrance to Presque Isle State Park. Famous for Erie-made Smith hot dogs and orange vanilla twists.",
    priceRange: "$",
    rating: 4.5,
    hours: "11:00 AM - 8:00 PM (Seasonal)",
    features: ["Takeout", "Family Friendly", "Ice Cream"],
    imageUrl: "/assets/sara-s.jpg"
  },
  {
    id: "2",
    name: "Federal Hill Smokehouse",
    category: "BBQ",
    categories: ["BBQ", "American"],
    address: "2609 Peach St, Erie, PA 16508",
    phone: "(814) 920-4695",
    website: "https://www.federalhillsmokehouse.com",
    description: "Award-winning BBQ with slow-smoked meats, homemade sides, and craft beer selection. Dog-friendly patio available.",
    priceRange: "$$",
    rating: 4.7,
    hours: "Mon-Sat 11:00 AM - 3:00 PM (or sell out), Sun Closed",
    features: ["Dine-in", "Takeout", "Pet Friendly", "Outdoor Seating"],
    imageUrl: "/assets/federal-hill.jpg"
  },
  {
    id: "3",
    name: "Bay House Oyster Bar & Restaurant",
    category: "Seafood",
    categories: ["Seafood", "Fine Dining"],
    address: "6 Sassafras Pier, Erie, PA 16507",
    phone: "(814) 413-7440",
    website: "https://www.bayhousepier6.com",
    description: "Erie's only fresh oyster bar offering stunning waterfront views, fresh seafood, and an exceptional dining experience.",
    priceRange: "$$$",
    rating: 4.8,
    hours: "Mon-Thu 11:00 AM - 10:00 PM, Fri-Sat 11:00 AM - 11:00 PM, Sun 10:00 AM - 9:00 PM",
    features: ["Dine-in", "Waterfront", "Full Bar", "Reservations"],
    imageUrl: "/assets/bay-house.jpg"
  },
  {
    id: "4",
    name: "Oliver's Rooftop",
    category: "American",
    categories: ["American", "Bar & Grill", "Fine Dining"],
    address: "130 E Front St, Erie, PA 16507",
    phone: "(814) 920-9666",
    website: "https://oliversrooftop.com",
    description: "Erie's premier rooftop dining experience with stunning skyline views. Upscale American cuisine, craft cocktails, and an unforgettable atmosphere on the eighth floor.",
    priceRange: "$$$",
    rating: 4.6,
    hours: "Mon-Thu 11:00 AM - 10:00 PM, Fri-Sat 11:00 AM - 11:00 PM, Sun 10:00 AM - 10:00 PM",
    features: ["Dine-in", "Rooftop", "Full Bar", "Reservations"],
    imageUrl: "/assets/olivers.jpeg"
  },
  {
    id: "5",
    name: "Thai Taste Cuisine",
    category: "Asian",
    categories: ["Asian", "Thai"],
    address: "35 Peninsula Dr, Erie, PA 16505",
    phone: "(814) 920-4125",
    website: "https://www.thaitasteerie.com/",
    description: "Authentic Thai cuisine with fresh ingredients. Try their famous Pad Thai and curry dishes.",
    priceRange: "$$",
    rating: 4.4,
    hours: "11:00 AM - 9:30 PM",
    features: ["Dine-in", "Takeout", "Vegetarian Options"]
  },
  {
    id: "6",
    name: "Tandoori Hut",
    category: "Indian",
    categories: ["Indian", "Vegetarian"],
    address: "2605 Washington Ave, Erie, PA 16508",
    phone: "(814) 920-4313",
    description: "Traditional Indian cuisine with a variety of vegetarian and meat options. Known for their tandoori dishes and naan bread.",
    priceRange: "$$",
    rating: 4.3,
    hours: "Mon-Sat 11:00 AM - 8:00 PM, Sun Closed",
    features: ["Dine-in", "Takeout", "Lunch Buffet", "Vegetarian Options"]
  },
  {
    id: "7",
    name: "El Canelo Mexican Restaurant",
    category: "Mexican",
    categories: ["Mexican"],
    address: "2709 Parade St, Erie, PA 16504",
    phone: "(814) 453-6288",
    description: "Authentic Mexican cuisine with fresh ingredients and traditional recipes. Known for their flavorful tacos, enchiladas, and house-made salsas.",
    priceRange: "$$",
    rating: 4.5,
    hours: "11:00 AM - 9:00 PM",
    features: ["Dine-in", "Takeout", "Delivery"],
    imageUrl: "/assets/el-canelo.png"
  },
  {
    id: "8",
    name: "Cloud 9 Wine Bar & Restaurant",
    category: "Fine Dining",
    categories: ["Fine Dining", "Mediterranean"],
    address: "25 E 10th St, Erie, PA 16501",
    phone: "(814) 870-9007",
    website: "https://cloud9erie.com",
    description: "French-inspired upscale dining with thoughtfully chosen wines paired with skillfully prepared dishes.",
    priceRange: "$$$$",
    rating: 4.7,
    hours: "Sun-Mon Closed, Tue-Thu 4:00 PM - 10:00 PM, Fri-Sat 4:00 PM - 12:00 AM",
    features: ["Dine-in", "Wine Bar", "Reservations", "Fine Dining"]
  },
  {
    id: "9",
    name: "Bar Ronin",
    category: "Asian",
    categories: ["Asian", "American", "Bar & Grill"],
    address: "948 W Erie Plaza Dr, Erie, PA 16505",
    phone: "(814) 920-4100",
    website: "https://roninerie.com",
    description: "American-Japanese fusion with shareable plates and standout cocktails. A chef-driven hotspot in downtown Erie.",
    priceRange: "$$$",
    rating: 4.8,
    hours: "Mon Closed, Tue-Thu 5:00 PM - 10:00 PM, Fri-Sat 5:00 PM - 12:00 AM",
    features: ["Dine-in", "Full Bar", "Cocktails", "Late Night"]
  },
  {
    id: "10",
    name: "Samurai Kitchen and Sushi",
    category: "Asian",
    categories: ["Asian", "Seafood"],
    address: "2767 W 12th St, Erie, PA 16505",
    phone: "(814) 833-0293",
    website: "https://www.samuraisushierie.com",
    description: "High-quality Japanese and Southeast Asian dishes with artful sushi rolls and vibrant entrees.",
    priceRange: "$$$",
    rating: 4.6,
    hours: "Mon Closed, Tue-Thu 11:30 AM-2:30 PM & 4:00-9:00 PM, Fri 11:30 AM-2:30 PM & 4:00-10:00 PM, Sat 11:30 AM-10:00 PM, Sun Closed",
    features: ["Dine-in", "Takeout", "Sushi Bar"]
  },
  {
    id: "11",
    name: "Valerio's Italian Restaurant",
    category: "Italian",
    categories: ["Italian"],
    address: "544 W 18th St, Erie, PA 16502",
    phone: "(814) 452-4633",
    description: "Family-owned Italian restaurant serving homemade pasta, pizza, and classic Italian dishes since 1978.",
    priceRange: "$$",
    rating: 4.5,
    hours: "11:00 AM - 10:00 PM",
    features: ["Dine-in", "Takeout", "Family Style"]
  },
  {
    id: "12",
    name: "Shoreline Bar and Grille",
    category: "Bar & Grill",
    categories: ["Bar & Grill", "American", "Seafood"],
    address: "2 Sassafras Pier, Erie, PA 16507",
    phone: "(814) 636-1005",
    description: "Bayfront hotel restaurant offering stunning sunset views with food and drinks. Waterfront dining with panoramic views of Presque Isle Bay. Casual American fare with fresh seafood.",
    priceRange: "$$",
    rating: 4.3,
    hours: "11:30 AM - 10:00 PM",
    features: ["Dine-in", "Waterfront", "Outdoor Seating", "Full Bar", "Sunset Views"]
  },
  {
    id: "14",
    name: "Ippa Pizza Napoletana",
    category: "Pizza",
    categories: ["Pizza", "Italian"],
    address: "22 North Park Row, Erie, PA 16501",
    phone: "(814) 240-6599",
    description: "Authentic Neapolitan-style pizza made with fresh dough and imported ingredients. Available on major delivery apps.",
    priceRange: "$$",
    rating: 4.6,
    hours: "Mon-Fri 11:00 AM - 9:00 PM, Sat 12:00 PM - 9:00 PM, Sun Closed",
    features: ["Dine-in", "Takeout", "Delivery"]
  },
  {
    id: "15",
    name: "Sloppy Duck Saloon",
    category: "American",
    categories: ["American", "Seafood", "Bar & Grill"],
    address: "726 W Bayfront Pkwy, Erie, PA 16507",
    phone: "(814) 452-6699",
    website: "https://www.sloppyducksaloon.com",
    description: "Waterfront favorite known for the crispiest fried walleye sandwich. Seasonal outdoor seating with bay views.",
    priceRange: "$$",
    rating: 4.5,
    hours: "11:00 AM - 10:00 PM (Seasonal)",
    features: ["Dine-in", "Waterfront", "Full Bar", "Outdoor Seating"]
  },
  {
    id: "16",
    name: "Lucky Louie's Beer and Wieners",
    category: "American",
    categories: ["American", "Fast Food"],
    address: "8238 Perry Hwy (Route 97), Erie, PA 16509",
    phone: "(814) 314-9481",
    website: "https://luckylouiesbeerandwieners.com",
    description: "Unhinged and laid-back vibe with outrageous hot dog topping combinations, craft brews, and yard games.",
    priceRange: "$",
    rating: 4.4,
    hours: "Mon-Thu 11:00 AM - 8:00 PM, Fri-Sat 11:00 AM - 9:00 PM, Sun 11:00 AM - 8:00 PM",
    features: ["Dine-in", "Outdoor Seating", "Craft Beer", "Family Friendly"],
    imageUrl: "/assets/lucky-louies.jpg"
  },
  {
    id: "17",
    name: "Bakery on 5th",
    category: "Cafe",
    categories: ["Cafe", "Breakfast"],
    address: "502 State St, Erie, PA 16501",
    phone: "(814) 315-4517",
    description: "Artisan bakery known for oversized croissants and Turkish coffee. Perfect stop for pastries and coffee.",
    priceRange: "$",
    rating: 4.6,
    hours: "Mon-Thu 6:00 AM - 5:00 PM, Fri-Sat 6:00 AM - 7:00 PM, Sun 6:00 AM - 5:00 PM",
    features: ["Dine-in", "Takeout", "Coffee", "Pastries"]
  },
  {
    id: "18",
    name: "Quaker Steak & Lube",
    category: "American",
    categories: ["American", "Bar & Grill"],
    address: "8071 Peach St, Erie, PA 16503",
    phone: "(814) 217-1140",
    website: "https://thelube.com",
    description: "Motor-themed restaurant with famous wings and duckpin bowling. Fun for the whole family.",
    priceRange: "$$",
    rating: 4.2,
    hours: "Mon-Thu 11:00 AM - 10:00 PM, Fri-Sat 11:00 AM - 11:00 PM, Sun 11:00 AM - 10:00 PM",
    features: ["Dine-in", "Bowling", "Full Bar", "Family Friendly"]
  },
  {
    id: "19",
    name: "Two45 Waterfront Grille",
    category: "Fine Dining",
    categories: ["Fine Dining", "American", "Seafood"],
    address: "55 W Bay Dr, Erie, PA 16507",
    phone: "(814) 454-2011",
    description: "Upscale dining inside the Sheraton Erie Bayfront Hotel with panoramic waterfront views and refined American cuisine.",
    priceRange: "$$$",
    rating: 4.5,
    hours: "6:30 AM - 10:00 PM",
    features: ["Dine-in", "Waterfront", "Breakfast", "Reservations"],
    imageUrl: "/assets/two45.jpg"
  },
  {
    id: "20",
    name: "Flagship City Food Hall",
    category: "American",
    categories: ["American", "Asian", "Mexican"],
    address: "22 N Park Row, Erie, PA 16501",
    phone: "(814) 240-6599",
    website: "https://www.flagshipcitydistrict.com/foodhall",
    description: "Multiple local vendors under one roof offering diverse kid-friendly options and local favorites.",
    priceRange: "$$",
    rating: 4.3,
    hours: "Mon-Fri 6:00 AM - 9:00 PM, Sat 7:00 AM - 9:00 PM, Sun 7:00 AM - 7:00 PM",
    features: ["Dine-in", "Multiple Vendors", "Family Friendly"]
  },
  {
    id: "21",
    name: "Roma's Italian Kitchen",
    category: "Italian",
    categories: ["Italian", "Pizza"],
    address: "2933 W 12th St, Erie, PA 16505",
    phone: "(814) 651-0900",
    website: "https://www.romaserie.com",
    description: "Chef-inspired Italian cuisine brought to you by Scott Enterprises. Featuring homemade pasta, pizza, and classic Italian dishes with delivery and takeout options.",
    priceRange: "$$",
    rating: 4.5,
    hours: "Sun-Thu 11:00 AM - 9:00 PM, Fri-Sat 11:00 AM - 10:00 PM",
    features: ["Dine-in", "Takeout", "Delivery", "Outdoor Seating"]
  },
  {
    id: "22",
    name: "Colao's Ristorante",
    category: "Italian",
    categories: ["Italian", "Fine Dining"],
    address: "2826 Plum St, Erie, PA 16508",
    phone: "(814) 866-9621",
    website: "https://www.colaos.com",
    description: "Upscale Italian dining featuring traditional recipes passed down through generations. Known for exceptional wine selection and elegant atmosphere.",
    priceRange: "$$$",
    rating: 4.7,
    hours: "Mon-Sat 5:00 PM - 9:00 PM, Sun Closed",
    features: ["Dine-in", "Reservations", "Wine List", "Fine Dining"],
    imageUrl: "/assets/colaos.webp"
  },
  {
    id: "23",
    name: "A. Francisco's",
    category: "Italian",
    categories: ["Italian", "Pizza"],
    address: "1501 State St, Erie, PA 16501",
    phone: "(814) 455-8700",
    description: "Downtown Erie Italian favorite serving authentic dishes, wood-fired pizzas, and house-made desserts in a cozy urban setting.",
    priceRange: "$$",
    rating: 4.4,
    hours: "11:00 AM - 9:00 PM",
    features: ["Dine-in", "Takeout", "Wood-Fired Pizza", "Downtown"]
  },
  {
    id: "24",
    name: "Falcone's Kitchen",
    category: "Italian",
    categories: ["Italian", "Comfort Food"],
    address: "2643 Myrtle St, Erie, PA 16508",
    phone: "(814) 459-5855",
    description: "Neighborhood Italian kitchen known for generous portions, family recipes, and a casual, friendly atmosphere. A local favorite for comfort food.",
    priceRange: "$$",
    rating: 4.3,
    hours: "11:00 AM - 9:00 PM",
    features: ["Dine-in", "Takeout", "Family Recipes", "Casual Dining"]
  },
  {
    id: "25",
    name: "Serafini's Trattoria",
    category: "Italian",
    categories: ["Italian"],
    address: "417 State St, Erie, PA 16501",
    phone: "(814) 310-8576",
    website: "https://eatserafinis.com",
    description: "Authentic Italian family cuisine cherished for generations. Featuring beloved classics including renowned spaghetti with meat sauce and mouthwatering meatballs in the historic Cashier House building.",
    priceRange: "$$",
    rating: 4.0,
    hours: "Tue-Wed 11:00 AM - 3:00 PM, Thu 11:00 AM - 3:00 PM, Fri 11:00 AM - 2:30 PM & 4:00 PM - 10:00 PM, Sat 4:00 PM - 10:00 PM, Sun 3:00 PM - 8:00 PM",
    features: ["Dine-in", "Family Recipes", "Historic Location"],
    imageUrl: "/assets/serafinis.jpg"
  },
  {
    id: "26",
    name: "Pineapple Eddie Southern Bistro",
    category: "American",
    categories: ["American", "Fine Dining"],
    address: "1402 W 10th St, Erie, PA 16502",
    phone: "(814) 454-1010",
    description: "Southern-inspired cuisine with a creative twist. Upscale dining featuring locally sourced ingredients.",
    priceRange: "$$$",
    rating: 4.6,
    hours: "5:00 PM - 9:00 PM",
    features: ["Dine-in", "Full Bar", "Reservations"]
  },
  {
    id: "27",
    name: "McGarrey's Oakwood Cafe",
    category: "American",
    categories: ["American", "Irish", "Bar & Grill"],
    address: "1624 W 38th St, Erie, PA 16508",
    phone: "(814) 866-0552",
    website: "https://www.mcgarreys.com",
    description: "Erie institution since 1978 serving classic American and Irish pub fare. Known for their wings, burgers, and friendly neighborhood atmosphere.",
    priceRange: "$$",
    rating: 4.4,
    hours: "Mon-Sat 11:00 AM - 10:00 PM, Sun 11:00 AM - 8:00 PM",
    features: ["Dine-in", "Full Bar", "Late Night", "Wings"],
    imageUrl: "/assets/mcgarreys.png"
  },
  {
    id: "28",
    name: "Torero's Authentic Mexican",
    category: "Mexican",
    categories: ["Mexican"],
    address: "2620 W 8th St, Erie, PA 16505",
    phone: "(814) 833-0298",
    description: "Authentic Mexican cuisine featuring traditional recipes, fresh ingredients, and a festive atmosphere. Known for their sizzling fajitas and margaritas.",
    priceRange: "$$",
    rating: 4.3,
    hours: "11:00 AM - 10:00 PM",
    features: ["Dine-in", "Takeout", "Full Bar", "Family Friendly"],
    imageUrl: "/assets/toreros.png"
  },
  {
    id: "29",
    name: "Julius",
    category: "Mexican",
    categories: ["Mexican"],
    address: "1607 State St, Erie, PA 16501",
    phone: "(814) 315-9311",
    website: "https://juliuserie.square.site/",
    description: "Authentic Mexican restaurant serving traditional dishes made with fresh ingredients and family recipes.",
    priceRange: "$$",
    rating: 4.5,
    hours: "Mon-Wed Closed, Thu-Sat 5:00 PM - 9:00 PM, Sun 11:00 AM - 2:00 PM",
    features: ["Dine-in", "Takeout"],
    imageUrl: "/assets/Julius.jpg"
  },
  {
    id: "30",
    name: "Empanissah's",
    category: "Latin",
    categories: ["Latin"],
    address: "38 North Park Row, Erie, PA 16501",
    phone: "",
    website: "https://www.facebook.com/profile.php?id=61561961867814",
    description: "Latin cuisine featuring authentic empanadas and traditional dishes from across Latin America.",
    priceRange: "$$",
    rating: 4.5,
    features: ["Dine-in", "Takeout", "Catering"],
    imageUrl: "/assets/empanissahs.jpg"
  },
  {
    id: "31",
    name: "CheesErie",
    category: "American",
    categories: ["American", "Cafe"],
    address: "22 N Park Row, Erie, PA 16501",
    phone: "(814) 715-4609",
    website: "https://www.facebook.com/groups/1597285337222719/user/100070847396961",
    description: "Local restaurant specializing in delicious cheese-centric dishes and comfort food favorites.",
    priceRange: "$$",
    rating: 4.4,
    features: ["Dine-in", "Takeout"],
    imageUrl: "/assets/cheeserie.jpg"
  },
  {
    id: "32",
    name: "Main Street Cakery Cafe",
    category: "Cafe",
    categories: ["Cafe", "Bakery", "Breakfast"],
    address: "2900 Copperleaf Dr, Erie, PA 16509",
    phone: "(814) 651-0375",
    website: "https://www.mainstreetcakery.com/",
    description: "Charming bakery and cafe offering fresh-baked goods, artisan cakes, pastries, and light cafe fare.",
    priceRange: "$$",
    rating: 4.6,
    features: ["Dine-in", "Takeout", "Custom Cakes", "Catering"],
    imageUrl: "/assets/mainstreetcakery.jpg"
  },
  {
    id: "33",
    name: "Iron Stone Meadery",
    category: "Winery & Meadery",
    categories: ["Winery & Meadery", "Bar & Grill"],
    address: "2890 Copperleaf Dr, Ste 140, Erie, PA 16509",
    phone: "(814) 873-5957",
    website: "https://www.ironstonemeadery.com/",
    description: "Craft meadery producing handcrafted meads and honey wines. Tasting room with a cozy atmosphere.",
    priceRange: "$$",
    rating: 4.7,
    hours: "Sat 1:00 PM - 8:00 PM (Closed Mon-Fri, Sun)",
    features: ["Tasting Room", "Tours", "Local Products"],
    imageUrl: "/assets/ironstone.webp"
  }
];

// Erie, PA events data - sourced from VisitErie.com
export const events: Event[] = [
  {
    id: "1",
    title: "Tropidelic at King's Rook Club",
    category: "Music",
    date: "2026-01-16",
    time: "7:30 PM",
    venue: "King's Rook Club",
    address: "1921 Peach St, Erie, PA 16502",
    description: "Cleveland-based reggae/rock fusion band Tropidelic brings their high-energy show to Erie. Known for their infectious grooves and party atmosphere!",
    isFree: false,
    price: "$15-$25",
    ticketUrl: "https://www.kingsrookclub.com"
  },
  {
    id: "2",
    title: "Saginaw Spirit at Erie Otters",
    category: "Sports",
    date: "2026-01-17",
    time: "7:00 PM",
    venue: "Erie Insurance Arena",
    address: "809 French St, Erie, PA 16501",
    description: "OHL hockey action as the Erie Otters take on the Saginaw Spirit! Family-friendly entertainment with exciting junior hockey.",
    price: "$15-$35",
    isFree: false,
    ticketUrl: "https://www.ottershockey.com"
  },
  {
    id: "3",
    title: "A Magical Motown Christmas",
    category: "Music",
    date: "2026-01-17",
    time: "7:30 PM",
    venue: "Warner Theatre",
    address: "811 State St, Erie, PA 16501",
    description: "Experience the magic of Motown with this spectacular concert featuring classic hits from The Temptations, The Supremes, Marvin Gaye, and more!",
    isFree: false,
    price: "$35-$75",
    ticketUrl: "https://www.erieevents.com"
  },
  {
    id: "4",
    title: "Erie Restaurant Week 2026",
    category: "Food & Drink",
    date: "2026-01-22",
    time: "All Day",
    venue: "Various Restaurants",
    address: "Downtown Erie & Surrounding Areas",
    description: "Erie's biggest culinary celebration! Sample prix-fixe menus and special offerings from dozens of Erie's best restaurants at special prices. Week-long event!",
    isFree: false,
    price: "Prix-fixe menus",
    ticketUrl: "https://www.visiterie.com/events"
  },
  {
    id: "5",
    title: "Erie Kennel Club All-Breed Dog Show",
    category: "Community",
    date: "2026-01-24",
    time: "8:00 AM",
    venue: "Bayfront Convention Center",
    address: "1 Sassafras Pier, Erie, PA 16507",
    description: "AKC-sanctioned all-breed dog show featuring hundreds of beautiful dogs competing in conformation, obedience, and agility. Fun for the whole family!",
    isFree: false,
    price: "$10 adults, kids free",
    ticketUrl: "https://www.bayfront.com"
  },
  {
    id: "6",
    title: "Princess Brunch at The Cork 1794",
    category: "Family",
    date: "2026-01-24",
    time: "10:00 AM",
    endTime: "12:00 PM",
    venue: "The Cork 1794",
    address: "32 Main St, Girard, PA 16417",
    description: "A magical brunch experience where kids can meet their favorite princesses, enjoy special activities, crafts, and a delicious brunch menu.",
    isFree: false,
    price: "$25-$35",
    ticketUrl: "https://thecork1794.com"
  },
  {
    id: "7",
    title: "PA 250 Celebration at PSU Behrend",
    category: "Community",
    date: "2026-01-26",
    time: "6:00 PM",
    endTime: "8:00 PM",
    venue: "Junker Center at PSU Behrend",
    address: "4701 College Dr, Erie, PA 16563",
    description: "Celebrate Pennsylvania's 250th anniversary with historical exhibits, presentations, and community activities highlighting Erie County's role in American history.",
    isFree: true,
    ticketUrl: "https://psubehrend.psu.edu"
  },
  {
    id: "8",
    title: "Erie Junior Philharmonic Winter Concert",
    category: "Music",
    date: "2026-01-31",
    time: "7:30 PM",
    venue: "Warner Theatre",
    address: "811 State St, Erie, PA 16501",
    description: "The talented young musicians of the Erie Junior Philharmonic perform a diverse winter concert program. Support local youth arts!",
    isFree: false,
    price: "$10-$20",
    ticketUrl: "https://www.eriephil.org"
  },
  {
    id: "9",
    title: "Erie SeaWolves Opening Night",
    category: "Sports",
    date: "2026-04-03",
    time: "6:05 PM",
    venue: "UPMC Park",
    address: "110 E 10th St, Erie, PA 16501",
    description: "Kick off the baseball season with the Erie SeaWolves! Opening night festivities, fireworks, and family fun at UPMC Park.",
    isFree: false,
    price: "$10-$25",
    ticketUrl: "https://www.milb.com/erie"
  },
  {
    id: "10",
    title: "Erie SeaWolves: Moon Mammoths Night",
    category: "Sports",
    date: "2026-05-29",
    time: "6:05 PM",
    venue: "UPMC Park",
    address: "110 E 10th St, Erie, PA 16501",
    description: "The Erie SeaWolves transform into the Moon Mammoths for this special themed night! Special jerseys, promotions, and fun for all ages.",
    isFree: false,
    price: "$10-$25",
    ticketUrl: "https://www.milb.com/erie"
  }
];

// Sample activities/things to do data
export const activities: Activity[] = [
  {
    id: "1",
    name: "Presque Isle State Park",
    category: "Nature",
    audience: ["Kids", "Adults", "Family"],
    address: "301 Peninsula Dr, Erie, PA 16505",
    phone: "(814) 833-7424",
    website: "https://www.dcnr.pa.gov/StateParks/FindAPark/PresqueIsleStatePark",
    description: "Pennsylvania's most visited state park featuring 11 miles of sandy beaches, hiking trails, and stunning Lake Erie views.",
    hours: "5:00 AM - 11:00 PM",
    priceRange: "Free"
  },
  {
    id: "2",
    name: "ExpERIEnce Children's Museum",
    category: "Education",
    audience: ["Kids", "Family"],
    address: "420 French St, Erie, PA 16507",
    phone: "(814) 453-3743",
    website: "https://www.eriechildrensmuseum.org",
    description: "Interactive exhibits designed to inspire creativity and learning in children through hands-on play.",
    hours: "Tue-Sat 10:00 AM - 4:00 PM",
    priceRange: "$10"
  },
  {
    id: "3",
    name: "Erie Zoo",
    category: "Nature",
    audience: ["Kids", "Family"],
    address: "423 W 38th St, Erie, PA 16508",
    phone: "(814) 864-4091",
    website: "https://www.eriezoo.org",
    description: "Home to over 400 animals from around the world. Features a train ride, carousel, and seasonal attractions.",
    hours: "10:00 AM - 5:00 PM",
    priceRange: "$12-$14"
  },
  {
    id: "4",
    name: "Erie Maritime Museum & US Brig Niagara",
    category: "Arts & Culture",
    audience: ["Adults", "Family"],
    address: "150 E Front St, Erie, PA 16507",
    phone: "(814) 452-2744",
    website: "https://www.flagshipniagara.org",
    description: "Explore Erie's rich maritime history and tour the reconstructed US Brig Niagara, hero of the Battle of Lake Erie.",
    hours: "Thu-Sun 10:00 AM - 5:00 PM",
    priceRange: "$8-$10"
  },
  {
    id: "5",
    name: "Waldameer Park & Water World",
    category: "Entertainment",
    audience: ["Kids", "Adults", "Family"],
    address: "220 Peninsula Dr, Erie, PA 16505",
    phone: "(814) 838-3591",
    website: "https://www.waldameer.com",
    description: "Classic amusement park with roller coasters, water slides, and family rides. Free admission, pay-per-ride available.",
    hours: "Seasonal (May-Sept)",
    priceRange: "Free-$34"
  },
  {
    id: "6",
    name: "Erie Art Museum",
    category: "Arts & Culture",
    audience: ["Adults", "Family"],
    address: "20 E 5th St, Erie, PA 16507",
    phone: "(814) 459-5477",
    website: "https://www.erieartmuseum.org",
    description: "Regional art museum featuring American and international art spanning 5,000 years of creative expression.",
    hours: "Thu-Sun 11:00 AM - 5:00 PM",
    priceRange: "$8"
  },
  {
    id: "7",
    name: "Tom Ridge Environmental Center",
    category: "Nature",
    audience: ["Kids", "Adults", "Family"],
    address: "301 Peninsula Dr Suite 1, Erie, PA 16505",
    phone: "(814) 833-7424",
    description: "Free exhibits about Presque Isle's unique ecosystem, observation tower with panoramic views.",
    hours: "10:00 AM - 6:00 PM",
    priceRange: "Free"
  },
  {
    id: "8",
    name: "Peek'n Peak Resort",
    category: "Sports",
    audience: ["Adults", "Family"],
    address: "1405 Olde Rd, Clymer, NY 14724",
    phone: "(716) 355-4141",
    website: "https://www.pknpk.com",
    description: "Year-round resort offering skiing, snowboarding, golf, zip lining, and spa services.",
    hours: "Varies by season",
    priceRange: "$45-$85"
  },
  {
    id: "9",
    name: "Splash Lagoon Indoor Water Park",
    category: "Entertainment",
    audience: ["Kids", "Family"],
    address: "8091 Peach St, Erie, PA 16509",
    phone: "(814) 217-1111",
    website: "https://www.splashlagoon.com",
    description: "Indoor water park featuring slides, wave pools, and attractions for all ages. Perfect for year-round fun!",
    hours: "10:00 AM - 9:00 PM",
    priceRange: "$35-$50"
  },
  {
    id: "10",
    name: "Escape Game Erie",
    category: "Entertainment",
    audience: ["Adults", "Family"],
    address: "3003 W 12th St, Erie, PA 16505",
    phone: "(814) 315-9100",
    description: "Immersive escape room experiences with multiple themed rooms. Great for team building and family fun.",
    hours: "Tue-Sun 12:00 PM - 10:00 PM",
    priceRange: "$28-$35"
  },
  {
    id: "11",
    name: "Warner Theatre",
    category: "Arts & Culture",
    audience: ["Adults", "Family"],
    address: "811 State St, Erie, PA 16501",
    phone: "(814) 452-4857",
    website: "https://www.erieevents.com",
    description: "Historic 1931 movie palace now hosting concerts, Broadway shows, and special events.",
    hours: "Varies by event",
    priceRange: "Varies"
  },
  {
    id: "12",
    name: "Presque Isle Lighthouse",
    category: "Tours",
    audience: ["Adults", "Family"],
    address: "Presque Isle State Park, Erie, PA 16505",
    phone: "(814) 833-7424",
    description: "Historic lighthouse dating to 1873 offering tours and stunning views of Lake Erie.",
    hours: "Seasonal tours available",
    priceRange: "Free"
  },
  {
    id: "13",
    name: "Lake Erie Canopy Tours",
    category: "Outdoor",
    audience: ["Adults", "Family"],
    address: "5480 Rt 430, Bemus Point, NY 14712",
    phone: "(716) 720-9477",
    description: "Thrilling zipline adventure through the forest canopy with views of the lake region.",
    hours: "Seasonal",
    priceRange: "$65-$95"
  },
  {
    id: "14",
    name: "Millcreek Mall",
    category: "Shopping",
    audience: ["Adults", "Family"],
    address: "5800 Peach St, Erie, PA 16565",
    phone: "(814) 868-9000",
    website: "https://www.millcreekmall.net",
    description: "Region's largest shopping destination with over 150 stores, restaurants, and entertainment.",
    hours: "10:00 AM - 9:00 PM",
    priceRange: "Varies"
  },
  {
    id: "15",
    name: "Bicentennial Tower",
    category: "Scenic Views",
    audience: ["Adults", "Family"],
    address: "1 State St, Erie, PA 16507",
    phone: "(814) 455-6055",
    description: "Observation tower offering panoramic sunset views from 187 feet up. Perfect for capturing breathtaking scenes over the bay and city with unobstructed 360-degree views of Erie, Presque Isle, and Lake Erie.",
    hours: "10:00 AM - 8:00 PM (Seasonal)",
    priceRange: "$4"
  },
  {
    id: "16",
    name: "Sunset Point at Presque Isle",
    category: "Scenic Views",
    audience: ["Adults", "Family", "Kids"],
    address: "Presque Isle State Park, Erie, PA 16505",
    phone: "(814) 833-7424",
    website: "https://www.dcnr.pa.gov/StateParks/FindAPark/PresqueIsleStatePark",
    description: "Considered the most photogenic spot in Erie with unparalleled sunset views over Lake Erie. This iconic location offers pristine beach access and stunning natural scenery.",
    hours: "5:00 AM - 11:00 PM",
    priceRange: "Free"
  },
  {
    id: "17",
    name: "Lighthouse Beach at Presque Isle",
    category: "Scenic Views",
    audience: ["Adults", "Family", "Kids"],
    address: "Presque Isle State Park, Erie, PA 16505",
    phone: "(814) 833-7424",
    website: "https://www.dcnr.pa.gov/StateParks/FindAPark/PresqueIsleStatePark",
    description: "Tranquil sunset spot within Presque Isle offering peaceful lake views and sandy shoreline. Perfect for unobstructed sunset photography and evening beach walks.",
    hours: "5:00 AM - 11:00 PM",
    priceRange: "Free"
  },
  {
    id: "18",
    name: "Waterworks Beach at Presque Isle",
    category: "Scenic Views",
    audience: ["Adults", "Family", "Kids"],
    address: "Presque Isle State Park, Erie, PA 16505",
    phone: "(814) 833-7424",
    website: "https://www.dcnr.pa.gov/StateParks/FindAPark/PresqueIsleStatePark",
    description: "Great option within the park for tranquil sunset settings and unobstructed lake views. Popular spot for families and photographers seeking stunning evening scenes.",
    hours: "5:00 AM - 11:00 PM",
    priceRange: "Free"
  },
  {
    id: "19",
    name: "Erie Bluffs State Park",
    category: "Scenic Views",
    audience: ["Adults", "Family"],
    address: "11100 W Lake Rd, Lake City, PA 16423",
    phone: "(814) 833-0351",
    website: "https://www.dcnr.pa.gov/StateParks/FindAPark/ErieBluffsStatePark",
    description: "One of the great sunset spots in Erie, featuring dramatic bluff views overlooking Lake Erie. Offers elevated perspectives and natural beauty for sunset enthusiasts.",
    hours: "Sunrise to Sunset",
    priceRange: "Free"
  },
  {
    id: "20",
    name: "Walnut Creek Access",
    category: "Scenic Views",
    audience: ["Adults", "Family"],
    address: "Walnut Creek Access, Erie, PA",
    description: "Scenic waterfront access point offering spectacular sunset views over Lake Erie. A hidden gem for those seeking peaceful evening vistas away from crowds.",
    hours: "Dawn to Dusk",
    priceRange: "Free"
  },
  {
    id: "21",
    name: "Dobbins Landing",
    category: "Scenic Views",
    audience: ["Adults", "Family", "Kids"],
    address: "State St, Erie, PA 16507",
    description: "The area around the Bicentennial Tower provides ground-level sunset views of the bay. Popular waterfront destination for evening strolls and sunset watching with nearby amenities.",
    hours: "Open 24 hours",
    priceRange: "Free"
  }
];

// Sample autism programs data
export const autismPrograms: AutismProgram[] = [
  {
    id: "1",
    name: "Autism Society of Northwestern Pennsylvania",
    organization: "Autism Society NWPA",
    description: "Providing education, advocacy, and support services for individuals with autism and their families throughout Northwestern Pennsylvania.",
    address: "3340 Peach St, Erie, PA 16508",
    phone: "(814) 455-3540",
    email: "info@autismnwpa.org",
    website: "https://www.autismnwpa.org",
    services: ["Support Groups", "Educational Workshops", "Advocacy", "Resource Navigation", "Family Events"],
    accessibility: ["Sensory-Friendly Environment", "Visual Supports", "Trained Staff"]
  },
  {
    id: "2",
    name: "Barber National Institute",
    organization: "Barber National Institute",
    description: "Comprehensive services for children and adults with autism including education, employment, and residential programs.",
    ageRange: "All ages",
    address: "100 Barber Pl, Erie, PA 16507",
    phone: "(814) 453-7661",
    website: "https://www.bfrce.org",
    services: ["Early Intervention", "Special Education", "Adult Day Programs", "Employment Services", "Residential Services", "Behavioral Health"],
    accessibility: ["Wheelchair Accessible", "Sensory Rooms", "ABA Therapy"]
  },
  {
    id: "3",
    name: "Achievement Center",
    organization: "The Achievement Center",
    description: "Providing therapy, education, and support services for children with developmental delays and disabilities.",
    ageRange: "Birth to 21 years",
    address: "4800 Zuck Rd, Erie, PA 16506",
    phone: "(814) 459-2755",
    website: "https://www.achievementctr.org",
    services: ["Occupational Therapy", "Speech Therapy", "Physical Therapy", "Social Skills Groups", "Summer Programs"],
    accessibility: ["Therapy Equipment", "Sensory Integration", "Individualized Plans"]
  },
  {
    id: "4",
    name: "Autism Diagnostic Services - UPMC Children's",
    organization: "UPMC Children's Hospital",
    description: "Comprehensive diagnostic evaluations and ongoing care for children with autism spectrum disorders.",
    ageRange: "Children and Adolescents",
    address: "310 E 2nd St, Erie, PA 16507",
    phone: "(814) 877-8200",
    website: "https://www.chp.edu/our-services/autism",
    services: ["Diagnostic Evaluations", "Developmental Assessments", "Care Coordination", "Family Support"],
    accessibility: ["Hospital Setting", "Specialized Medical Team", "Insurance Accepted"]
  },
  {
    id: "5",
    name: "GECAC Early Intervention",
    organization: "Greater Erie Community Action Committee",
    description: "Early intervention services for infants and toddlers with developmental delays or at risk for delays.",
    ageRange: "Birth to 3 years",
    address: "18 W 9th St, Erie, PA 16501",
    phone: "(814) 459-4581",
    website: "https://www.gecac.org",
    services: ["In-Home Services", "Family Training", "Developmental Therapy", "Service Coordination"],
    accessibility: ["Home-Based Services", "Free Services", "Multilingual Support"]
  },
  {
    id: "6",
    name: "Sarah Reed Children's Center",
    organization: "Sarah Reed Children's Center",
    description: "Mental health and autism services for children including residential treatment and outpatient programs.",
    ageRange: "5-18 years",
    address: "2445 W 34th St, Erie, PA 16506",
    phone: "(814) 838-1954",
    website: "https://www.sarahreed.org",
    services: ["Residential Treatment", "Outpatient Therapy", "Crisis Services", "School-Based Programs"],
    accessibility: ["24/7 Support", "Specialized Staff", "Crisis Intervention"]
  },
  {
    id: "7",
    name: "Sensory-Friendly Movie Events",
    organization: "Tinseltown Erie",
    description: "Regular sensory-friendly movie screenings with adjusted lighting, lower volume, and freedom to move around.",
    address: "1910 Rotunda Dr, Erie, PA 16509",
    phone: "(814) 866-0123",
    services: ["Sensory-Friendly Screenings", "Reduced Stimulation", "Family-Friendly Environment"],
    accessibility: ["Lights Dimmed", "Lower Volume", "Movement Allowed", "Wheelchair Accessible"]
  },
  {
    id: "8",
    name: "Autism-Friendly Swim Program",
    organization: "Erie Family YMCA",
    description: "Specialized swimming lessons for individuals with autism in a calm, supportive environment.",
    ageRange: "All ages",
    address: "31 W 10th St, Erie, PA 16501",
    phone: "(814) 452-3261",
    website: "https://www.ymcaerie.org",
    services: ["Private Lessons", "Small Group Classes", "Sensory-Friendly Times", "Trained Instructors"],
    accessibility: ["Pool Accessibility", "Quiet Hours", "Visual Schedules"]
  },
  {
    id: "9",
    name: "Taylor's Hope",
    organization: "Taylor's Hope",
    description: "Non-profit organization dedicated to supporting the Erie community through various charitable programs and initiatives.",
    address: "Erie, PA",
    phone: "",
    website: "https://taylors-hope.org/",
    services: ["Community Support", "Charitable Programs", "Local Initiatives"],
    accessibility: [],
    imageUrl: "/assets/taylorshope.jpg"
  },
  {
    id: "10",
    name: "Heberle's Heartstrings",
    organization: "Heberle's Heartstrings",
    description: "Non-profit providing musical instrument lending and music education resources to the Erie community. Making music accessible to all.",
    address: "Erie, PA",
    phone: "",
    website: "https://www.heberlesheartstrings.org/",
    services: ["Instrument Lending", "Music Education", "Community Outreach", "Youth Programs"],
    accessibility: [],
    imageUrl: "/assets/heberles.jpg"
  },
  {
    id: "11",
    name: "NAMI Erie",
    organization: "National Alliance on Mental Illness - Erie Chapter",
    description: "Non-profit organization providing mental health support, education, and advocacy for individuals and families affected by mental illness.",
    address: "Erie, PA",
    phone: "",
    website: "https://namierie.org/",
    services: ["Mental Health Support", "Education Programs", "Advocacy", "Family Support", "Support Groups"],
    accessibility: [],
    imageUrl: "/assets/nami.jpg"
  },
  {
    id: "12",
    name: "KaleidAScope, Inc.",
    organization: "KaleidAScope, Inc. (KAS)",
    description: "Private non-profit 501(C)(3) providing Knowledge, Advocacy and Support for individuals on the Autism Spectrum and those with intellectual and developmental disabilities (IDD). Focuses on maximizing potential, independence, and community integration.",
    ageRange: "School age through adulthood",
    address: "337 W 10th St, Erie, PA 16502",
    phone: "(814) 824-4515",
    website: "https://www.kaserieinc.org",
    services: ["Individual Therapy", "Family Therapy", "Group Therapy", "Social Skills Groups", "Community Inclusion", "Behavior Support", "Employment Support", "PA Adult Autism Waiver", "ABA Therapy"],
    accessibility: ["Licensed Clinicians", "Insurance Accepted", "Waiver Services", "Community-Based Support"]
  }
];

// Sample social groups data
export const socialGroups: SocialGroup[] = [
  {
    id: "1",
    name: "Erie Young Professionals",
    category: "Professional Networking",
    description: "Networking group for professionals ages 21-40 focused on career development, community involvement, and social connections.",
    meetingSchedule: "Monthly networking events",
    location: "Various locations throughout Erie",
    contactEmail: "info@erieyps.org",
    website: "https://www.erieyps.org",
    membershipFee: "$50/year"
  },
  {
    id: "2",
    name: "Erie Running Club",
    category: "Sports & Fitness",
    description: "Community of runners of all skill levels meeting for group runs, training programs, and local race participation.",
    meetingSchedule: "Saturdays 8:00 AM, Tuesdays 6:00 PM",
    location: "Presque Isle State Park",
    contactEmail: "erierunners@gmail.com",
    membershipFee: "Free"
  },
  {
    id: "3",
    name: "Lake Erie Hiking Club",
    category: "Outdoor Recreation",
    description: "Explore the trails and natural beauty of the Lake Erie region with fellow outdoor enthusiasts.",
    meetingSchedule: "Weekly hikes on weekends",
    location: "Various trails in Erie County",
    website: "https://www.meetup.com/lake-erie-hiking-club",
    membershipFee: "Free"
  },
  {
    id: "4",
    name: "Erie Moms Group",
    category: "Parenting",
    description: "Support network for mothers in the Erie area featuring playdates, mom nights out, and family activities.",
    meetingSchedule: "Multiple weekly events",
    location: "Various family-friendly locations",
    contactEmail: "eriemomsgroup@gmail.com",
    membershipFee: "Free"
  },
  {
    id: "5",
    name: "Erie Board Game Enthusiasts",
    category: "Hobbies",
    description: "Weekly gatherings for board game lovers to play both classic and modern tabletop games.",
    meetingSchedule: "Wednesdays 6:00 PM",
    location: "Time Warp Games, 5865 Peach St",
    membershipFee: "Free"
  },
  {
    id: "6",
    name: "Erie Photography Club",
    category: "Arts & Creative",
    description: "Club for photographers of all skill levels to share work, learn techniques, and participate in photo walks.",
    meetingSchedule: "2nd Tuesday of each month",
    location: "Erie Art Museum",
    contactEmail: "eriephotoclub@gmail.com",
    membershipFee: "$25/year"
  },
  {
    id: "7",
    name: "Erie Rotary Club",
    category: "Service & Volunteer",
    description: "International service organization focused on community service, ethical standards, and goodwill.",
    meetingSchedule: "Thursdays 12:00 PM",
    location: "Sheraton Erie Bayfront Hotel",
    website: "https://www.erierotary.org",
    membershipFee: "Annual dues apply"
  },
  {
    id: "8",
    name: "Erie Writers' Workshop",
    category: "Arts & Creative",
    description: "Supportive community for writers of all genres to share work, receive feedback, and improve craft.",
    meetingSchedule: "1st and 3rd Saturdays 10:00 AM",
    location: "Blasco Memorial Library",
    contactEmail: "eriewriters@gmail.com",
    membershipFee: "Free"
  },
  {
    id: "9",
    name: "Erie Foodies",
    category: "Food & Dining",
    description: "Group of food enthusiasts exploring Erie's dining scene, hosting potlucks, and sharing culinary adventures.",
    meetingSchedule: "Monthly restaurant outings",
    location: "Various Erie restaurants",
    website: "https://www.meetup.com/erie-foodies",
    membershipFee: "Free"
  },
  {
    id: "10",
    name: "Erie Ski Club",
    category: "Sports & Fitness",
    description: "Winter sports enthusiasts organizing ski trips, lessons, and social events for members of all skill levels.",
    meetingSchedule: "Seasonal meetings and trips",
    location: "Peek'n Peak and other resorts",
    website: "https://www.erieskiclub.org",
    membershipFee: "$45/year"
  },
  {
    id: "11",
    name: "Single Parents of Erie",
    category: "Parenting",
    description: "Support and social group for single parents to connect, share experiences, and organize family activities.",
    meetingSchedule: "Bi-weekly gatherings",
    location: "Various family-friendly locations",
    contactEmail: "singleparentserie@gmail.com",
    membershipFee: "Free"
  },
  {
    id: "12",
    name: "Erie Garden Club",
    category: "Hobbies",
    description: "Gardening enthusiasts sharing knowledge, hosting plant sales, and beautifying Erie through community projects.",
    meetingSchedule: "3rd Wednesday of each month",
    location: "Frontier Park",
    contactPhone: "(814) 555-1234",
    membershipFee: "$20/year"
  },
  {
    id: "13",
    name: "Gogh Party Erie",
    category: "Arts & Creative",
    description: "Community painting group bringing people together for fun, social painting events. No experience necessary - just come and create!",
    meetingSchedule: "Regular painting events",
    location: "Various locations in Erie",
    website: "https://www.facebook.com/groups/668392443222569/user/100076898271397",
    membershipFee: "Free",
    imageUrl: "/assets/goghparty.jpg"
  }
];

// Sample Erie, PA local business data
export const businesses: Business[] = [
  {
    id: "1",
    name: "Pointe Foure",
    category: "Clothing & Fashion",
    categories: ["Clothing & Fashion", "Gifts & Specialty"],
    address: "2501 W 12th St, Erie, PA 16505",
    phone: "(814) 838-6111",
    website: "https://www.pointefoure.com",
    description: "Upscale women's boutique featuring designer clothing, accessories, and gifts. Personalized styling services available.",
    hours: "Mon-Sat 10:00 AM - 6:00 PM",
    features: ["Boutique", "Designer Clothing", "Personal Styling", "Gifts"]
  },
  {
    id: "2",
    name: "Pressed Books & Coffee",
    category: "Retail",
    categories: ["Retail", "Entertainment"],
    address: "1535 W 8th St, Erie, PA 16505",
    phone: "(814) 520-8451",
    website: "https://www.pressedbookscoffee.com",
    description: "Independent bookstore and coffee shop with curated book selection, local art, and craft coffee drinks.",
    hours: "Mon-Sat 8:00 AM - 8:00 PM, Sun 10:00 AM - 6:00 PM",
    features: ["Bookstore", "Coffee Shop", "Local Art", "Events"]
  },
  {
    id: "3",
    name: "Glass Growers Gallery",
    category: "Retail",
    categories: ["Retail", "Gifts & Specialty"],
    address: "10 E 5th St, Erie, PA 16507",
    phone: "(814) 453-3758",
    website: "https://www.glassgrowersgallery.com",
    description: "Contemporary craft gallery featuring handmade jewelry, pottery, glass art, and unique gifts from American artists.",
    hours: "Tue-Sat 10:00 AM - 5:00 PM",
    features: ["Art Gallery", "Handmade Jewelry", "Pottery", "Gifts"]
  },
  {
    id: "4",
    name: "Presque Isle Printing",
    category: "Professional Services",
    categories: ["Professional Services"],
    address: "2662 W 8th St, Erie, PA 16505",
    phone: "(814) 833-9020",
    website: "https://www.presqueisleprinting.com",
    description: "Full-service print shop offering business cards, banners, signs, apparel printing, and promotional products.",
    hours: "Mon-Fri 8:30 AM - 5:00 PM",
    features: ["Printing", "Signs & Banners", "Apparel", "Promotional Items"]
  },
  {
    id: "5",
    name: "LECOM Health & Fitness Center",
    category: "Fitness",
    categories: ["Fitness", "Health & Wellness"],
    address: "5401 Peach St, Erie, PA 16509",
    phone: "(814) 868-1400",
    website: "https://www.lecomwellness.com",
    description: "State-of-the-art fitness facility with cardio and weight equipment, group classes, pool, and personal training.",
    hours: "Mon-Fri 5:00 AM - 10:00 PM, Sat-Sun 7:00 AM - 7:00 PM",
    features: ["Gym", "Pool", "Group Classes", "Personal Training"]
  },
  {
    id: "6",
    name: "Panache Salon & Spa",
    category: "Beauty & Spa",
    categories: ["Beauty & Spa"],
    address: "5765 Peach St, Erie, PA 16509",
    phone: "(814) 866-4247",
    website: "https://www.panacheerie.com/",
    description: "Full-service salon and spa offering hair styling, coloring, facials, massages, and nail services.",
    hours: "Tue-Thu 9:00 AM - 8:00 PM, Fri-Sat 9:00 AM - 5:00 PM",
    features: ["Hair Salon", "Spa Services", "Nails", "Massage"]
  },
  {
    id: "9",
    name: "Potratz Floral Shop",
    category: "Florist",
    categories: ["Florist", "Gifts & Specialty"],
    address: "2619 Peach St, Erie, PA 16508",
    phone: "(814) 456-6467",
    website: "https://www.potratzfloral.com",
    description: "Family-owned florist since 1932 creating beautiful arrangements for weddings, events, and everyday occasions.",
    hours: "Mon-Fri 9:00 AM - 5:00 PM, Sat 9:00 AM - 2:00 PM",
    features: ["Flowers", "Weddings", "Events", "Delivery"]
  },
  {
    id: "10",
    name: "Blasco Memorial Library",
    category: "Education",
    categories: ["Education", "Entertainment"],
    address: "160 E Front St, Erie, PA 16507",
    phone: "(814) 451-6900",
    website: "https://www.erielibrary.org",
    description: "Erie's main public library offering books, media, computers, programs, and the renowned Idea Lab makerspace.",
    hours: "Mon-Thu 9:00 AM - 8:00 PM, Fri-Sat 9:00 AM - 5:00 PM",
    features: ["Library", "Makerspace", "Programs", "Free WiFi"]
  },
  {
    id: "11",
    name: "Whole Foods Co-op",
    category: "Grocery & Market",
    categories: ["Grocery & Market", "Health & Wellness"],
    address: "1341 W 26th St, Erie, PA 16508",
    phone: "(814) 456-0282",
    website: "https://www.wfcerie.coop",
    description: "Member-owned natural foods cooperative offering organic produce, bulk foods, local products, and health supplements.",
    hours: "Mon-Sat 8:00 AM - 8:00 PM, Sun 10:00 AM - 6:00 PM",
    features: ["Organic", "Local Products", "Bulk Foods", "Member-Owned"]
  },
  {
    id: "12",
    name: "Dramashop",
    category: "Entertainment",
    categories: ["Entertainment", "Education"],
    address: "1001 State St #210, Erie, PA 16501",
    phone: "(814) 580-8036",
    website: "https://www.dramashop.org",
    description: "Erie's premier destination for contemporary theater productions and acting classes for all ages.",
    hours: "Box office opens 1 hour before shows",
    features: ["Theater", "Acting Classes", "Live Performances", "Downtown"]
  },
  {
    id: "13",
    name: "Mazza Chautauqua Cellars",
    category: "Retail",
    categories: ["Retail", "Entertainment"],
    address: "8398 W Lake Rd, Lake City, PA 16423",
    phone: "(814) 725-5688",
    website: "https://www.mazzawines.com",
    description: "Award-winning winery offering tastings, tours, and a beautiful lakeside setting in Lake Erie Wine Country.",
    hours: "Mon-Sat 10:00 AM - 5:00 PM, Sun 12:00 PM - 5:00 PM",
    features: ["Wine Tasting", "Tours", "Event Space", "Lakeside"]
  },
  {
    id: "14",
    name: "Erie Insurance Arena Pro Shop",
    category: "Retail",
    categories: ["Retail", "Fitness"],
    address: "809 French St, Erie, PA 16501",
    phone: "(814) 452-4857",
    description: "Official merchandise store for Erie Otters and arena events. Team jerseys, apparel, and memorabilia.",
    hours: "Mon-Fri 10:00 AM - 5:00 PM, Event days extended",
    features: ["Sports Merchandise", "Team Apparel", "Memorabilia"]
  },
  {
    id: "15",
    name: "Creative Imprint Systems",
    category: "Professional Services",
    categories: ["Professional Services", "Printing"],
    address: "2670 West 11th Street, Erie, PA 16505",
    phone: "(814) 520-6045",
    website: "https://www.creativeimprintsystems.com/",
    description: "Professional printing and imprint services for businesses and individuals throughout Erie.",
    hours: "Mon-Fri 9:00 AM - 5:00 PM",
    features: ["Printing Services", "Custom Imprints", "Business Services", "Design"]
  },
  {
    id: "16",
    name: "John Gallagher DJ & Entertainment",
    category: "Entertainment",
    categories: ["Entertainment", "Professional Services"],
    address: "Erie, PA",
    phone: "",
    website: "https://www.johngallagher.com/",
    description: "Professional wedding and special event DJ services. Creating memorable experiences with music for your special occasions.",
    features: ["Wedding DJ", "Event Entertainment", "Special Events", "Professional Sound"],
    imageUrl: "/assets/johngallagher.jpg"
  },
  {
    id: "17",
    name: "Metamorphosis Counseling",
    category: "Health & Wellness",
    categories: ["Health & Wellness"],
    address: "Erie, PA",
    phone: "",
    website: "https://www.metamorphosiscounseling.net/",
    description: "Professional mental health counseling services providing compassionate care and support for individuals and families.",
    features: ["Mental Health", "Counseling", "Therapy", "Individual Sessions"],
    imageUrl: "/assets/metamorphosis.jpg"
  },
  {
    id: "18",
    name: "KD's Place Local Books & Arts",
    category: "Entertainment",
    categories: ["Entertainment", "Retail", "Education"],
    address: "Erie, PA",
    phone: "",
    website: "https://www.facebook.com/kdsplace814/",
    description: "Community event space featuring local books, arts, and cultural programming. A gathering place for Erie's creative community.",
    features: ["Event Space", "Local Books", "Arts", "Community Events"],
    imageUrl: "/assets/kdsplace.jpg"
  },
  {
    id: "19",
    name: "Sacred Energy Yoga",
    category: "Fitness",
    categories: ["Fitness", "Health & Wellness"],
    address: "Erie, PA",
    phone: "",
    website: "https://www.facebook.com/groups/668392443222569/user/61579081396134/",
    description: "Yoga studio offering classes for all levels. Find your inner peace and physical wellness through guided yoga practice.",
    features: ["Yoga Classes", "All Levels", "Wellness", "Meditation"],
    imageUrl: "/assets/sacredenergyyoga.jpg"
  },
  {
    id: "20",
    name: "Carolina - Erie Wedding Ceremonies",
    category: "Professional Services",
    categories: ["Professional Services"],
    address: "Erie, PA",
    phone: "",
    website: "https://www.facebook.com/Weddingceremonybykarolina",
    description: "Professional wedding officiant services for beautiful and personalized wedding ceremonies in the Erie area.",
    features: ["Wedding Officiant", "Custom Ceremonies", "Personalized Vows"],
    imageUrl: "/assets/karolinawed.jpg"
  },
  {
    id: "21",
    name: "Keller Williams Realty Erie",
    category: "Real Estate",
    categories: ["Real Estate", "Professional Services"],
    address: "Erie, PA",
    phone: "",
    website: "https://www.kellerwilliamseriepa.com/",
    description: "Full-service real estate agency helping buyers and sellers navigate the Erie housing market with expertise and care.",
    features: ["Real Estate", "Home Buying", "Home Selling", "Property Management"],
    imageUrl: "/assets/kwrealty.jpg"
  },
  {
    id: "22",
    name: "Calm Creations Jewelry",
    category: "Retail",
    categories: ["Retail", "Gifts & Specialty"],
    address: "Erie, PA",
    phone: "",
    website: "https://calmpermjewelry.glossgenius.com/",
    description: "Custom jewelry studio specializing in unique, handcrafted pieces. Permanent jewelry and custom designs available.",
    features: ["Custom Jewelry", "Handcrafted", "Permanent Jewelry", "Gift Items"],
    imageUrl: "/assets/calmcreations.jpg"
  },
  {
    id: "23",
    name: "Larese Floral",
    category: "Florist",
    categories: ["Florist", "Gifts & Specialty"],
    address: "Erie, PA",
    phone: "",
    website: "https://www.laresefloral.net/",
    description: "Family-owned Erie florist providing beautiful floral arrangements for all occasions. Specializing in weddings, funerals, events, and everyday celebrations with fresh, locally-sourced flowers.",
    features: ["Flowers", "Weddings", "Funerals", "Events", "Custom Arrangements", "Delivery", "Family-Owned"],
    imageUrl: "/assets/laresefloral.jpg",
    isFeatured: true
  },
  {
    id: "24",
    name: "Argyll Abbey",
    category: "Wedding Venue",
    categories: ["Wedding Venue"],
    address: "3854 Wheelertown Rd, Waterford, PA 16441",
    phone: "",
    website: "https://argyllabbeyestate.com/",
    description: "Elegant wedding venue estate offering beautiful settings for your special day.",
    features: ["Wedding Venue", "Event Space", "Outdoor Ceremonies", "Receptions"],
    imageUrl: "/assets/argyll_abbey.jpeg"
  }
];
